Essential Kit: AlertDialog
AlertDialog
Native UI
The AlertDialog class provides an interface to display an alert message to the user.
Public Member Functions
void AddTextInputField (TextInputFieldOptions options=null)
Adds a text input field to the alert.
void AddButton (string title, Callback callback)
Adds an action button to the alert. Here, the default style is used.
void AddButton (string title, Callback< string[]> callback)
Adds an action button to the alert. Here, the default style is used.
void AddCancelButton (string title, Callback callback)
Adds action button to the alert. This style type indicates the action cancels the operation and leaves things unchanged.
void Show ()
Shows the alert dialog to the user.
void Dismiss ()
Dismisses the alert dialog before user selects an action.
Static Public Member Functions
static AlertDialog CreateInstance (AlertDialogStyle alertStyle=AlertDialogStyle.Default)
Creates a new instance of the AlertDialog class.
Properties
string Title [get, set]
The title of the alert.
string Message [get, set]
The message of the alert.
Detailed Description
The following code example shows how to configure and present an alert dialog.
using UnityEngine;
using System.Collections;
using VoxelBusters.EssentialKit;
public class ExampleClass : MonoBehaviour
{
    public void Start()
    {
        AlertDialog newDialog   = AlertDialog.CreateInstance();
        newDialog.SetTitle(title);
        newDialog.SetMessage(message);
        newDialog.AddButton(button, OnAlertButtonClicked);
        newDialog.Show();
    }
    private void OnAlertButtonClicked()
    {
        // add your code
    }
}
Member Function Documentation
CreateInstance()
static AlertDialog CreateInstance (AlertDialogStyle alertStyle = AlertDialogStyle::Default) static
Parameters
alertStyle The alert style to be used.
Referenced by AlertDialogBuilder.AlertDialogBuilder().
AddTextInputField()
void AddTextInputField (TextInputFieldOptions options = null)
Parameters
options The options for the text input field built with TextInputFieldOptions.Builder.
Referenced by AlertDialogBuilder.AddTextInputField().
AddButton() [1/2]
void AddButton (string title, Callback callback)
Parameters
title The title of the button.
callback The method to execute when the user selects this button.
Referenced by AlertDialogBuilder.AddButton(), and AlertDialogBuilder.AddButton().
AddButton() [2/2]
void AddButton (string title, Callback< string[]> callback)
Parameters
title The title of the button.
callback The method to execute when the user selects this button which returns array of input text values, if any.
AddCancelButton()
void AddCancelButton (string title, Callback callback)
Parameters
title The title of the button.
callback The method to execute when the user selects this button.
Referenced by AlertDialogBuilder.AddCancelButton().
Property Documentation
Title
string Title get set
The title of the alert.
Message
string Message get set
The message of the alert.