Essential Kit: CloudServicesUtility
CloudServicesUtility
Cloud Services
Utility class for handling cloud services related operations.
Static Public Member Functions
static bool TryGetCloudAndLocalCacheValues< T > (string key, out T cloudValue, out T localCacheValue, T localCacheDefaultValue=default)
Gets the cloud and local cache value associated with the specified key.
Member Function Documentation
TryGetCloudAndLocalCacheValues< T >()
static bool TryGetCloudAndLocalCacheValues< T > (string key, out T cloudValue, out T localCacheValue, T localCacheDefaultValue = default) static
Template Parameters
T Specify the type of the value stored in cloud.
Parameters
key string used to identify the value stored in the cloud data store.
cloudValue The value available in Cloud storage.
localCacheValue The value available in local cache.
localCacheDefaultValue The default value to be used when specified key doesn't exist in local cache.
Returns
References CloudServices.GetBool(), CloudServices.GetByteArray(), CloudServices.GetDouble(), CloudServices.GetFloat(), CloudServices.GetInt(), CloudServices.GetLong(), and CloudServices.GetString().