var searchData=
[
  ['strong_0',['strong',['../index.html#highlights',1,'&lt;strong&gt;Highlights:&lt;/strong&gt;'],['../index.html#important-links',1,'&lt;strong&gt;Important links&lt;/strong&gt;'],['../index.html#third-party-plugins-compatibility',1,'&lt;strong&gt;Third Party Plugins Compatibility&lt;/strong&gt;']]],
  ['strong_20a_20true_20cross_20platform_20tool_20for_20unity_20which_20provides_20unique_20and_20unified_20way_20to_20access_20native_20functionality_20on_20mobile_20platforms_1',['&lt;strong&gt;Essential Kit (V3)&lt;/strong&gt; a true cross-platform tool for Unity which provides unique and unified way to access native functionality on mobile platforms.',['../index.html#essential-kit-v3-a-true-cross-platform-tool-for-unity-which-provides-unique-and-unified-way-to-access-native-functionality-on-mobile-platforms',1,'']]],
  ['strong_20essential_20kit_20v3_20strong_20a_20true_20cross_20platform_20tool_20for_20unity_20which_20provides_20unique_20and_20unified_20way_20to_20access_20native_20functionality_20on_20mobile_20platforms_2',['&lt;strong&gt;Essential Kit (V3)&lt;/strong&gt; a true cross-platform tool for Unity which provides unique and unified way to access native functionality on mobile platforms.',['../index.html#essential-kit-v3-a-true-cross-platform-tool-for-unity-which-provides-unique-and-unified-way-to-access-native-functionality-on-mobile-platforms',1,'']]],
  ['strong_20highlights_3a_20strong_3',['&lt;strong&gt;Highlights:&lt;/strong&gt;',['../index.html#highlights',1,'']]],
  ['strong_20important_20links_20strong_4',['&lt;strong&gt;Important links&lt;/strong&gt;',['../index.html#important-links',1,'']]],
  ['strong_20third_20party_20plugins_20compatibility_20strong_5',['&lt;strong&gt;Third Party Plugins Compatibility&lt;/strong&gt;',['../index.html#third-party-plugins-compatibility',1,'']]]
];
