Essential Kit: DatePicker
DatePicker sealed
Native UI
Provides a cross-platform interface to access device's date picker view.
Public Member Functions
DateTimeKind GetKind ()
Gets the DateTimeKind for the DatePicker.
DatePickerMode GetMode ()
Gets the DatePickerMode for the DatePicker.
DateTime? GetMinimumDate ()
Gets the minimum date that can be selected.
DateTime? GetMaximumDate ()
Gets the maximum date that can be selected.
DateTime? GetInitialDate ()
Gets the initial date set for the DatePicker.
DatePicker SetKind (DateTimeKind value)
Sets the DateTimeKind for the DatePicker.
DatePicker SetMinimumDate (DateTime? value)
Sets the minimum date that can be selected.
DatePicker SetMaximumDate (DateTime? value)
Sets the maximum date that can be selected.
DatePicker SetInitialDate (DateTime? value)
Sets the initial date that the picker will show.
void Show ()
Shows the date picker dialog to the user.
Static Public Member Functions
static DatePicker CreateInstance (DatePickerMode mode=DatePickerMode.DateAndTime)
Creates a new instance of the DatePicker class.
Public Attributes
ValueChangeCallback OnValueChange = delegate { }
Event triggered when the selected date value changes.
Callback< DatePickerResult > OnCloseCallback = delegate { }
Event triggered when the date picker is closed.
Member Function Documentation
CreateInstance()
static DatePicker CreateInstance (DatePickerMode mode = DatePickerMode::DateAndTime) static
Parameters
mode The picker mode to be used.
GetKind()
DateTimeKind GetKind ()
Returns
The DateTimeKind.
GetMode()
DatePickerMode GetMode ()
Returns
The DatePickerMode.
GetMinimumDate()
DateTime? GetMinimumDate ()
Returns
The minimum date.
GetMaximumDate()
DateTime? GetMaximumDate ()
Returns
The maximum date.
GetInitialDate()
DateTime? GetInitialDate ()
Returns
The initial date.
SetKind()
DatePicker SetKind (DateTimeKind value)
Parameters
value The DateTimeKind to set.
Returns
The DatePicker instance.
References DatePicker.SetInitialDate(), DatePicker.SetMaximumDate(), and DatePicker.SetMinimumDate().
SetMinimumDate()
DatePicker SetMinimumDate (DateTime? value)
Parameters
value The minimum date to set.
Returns
The DatePicker instance.
References DatePicker.SetInitialDate().
Referenced by DatePicker.SetKind().
SetMaximumDate()
DatePicker SetMaximumDate (DateTime? value)
Parameters
value The maximum date to set.
Returns
The DatePicker instance.
Referenced by DatePicker.SetKind().
SetInitialDate()
DatePicker SetInitialDate (DateTime? value)
Parameters
value The initial date to set.
Returns
The DatePicker instance.
Referenced by DatePicker.SetKind(), and DatePicker.SetMinimumDate().