Essential Kit: SharingServices
SharingServices
Sharing Services
Provides a cross-platform interface to access sharing services.
Static Public Member Functions
static void ShowMailComposer (string[] toRecipients=null, string[] ccRecipients=null, string[] bccRecipients=null, string subject=null, string body=null, bool isHtmlBody=false, EventCallback< MailComposerResult > callback=null, params ShareItem[] shareItems)
Shows the mail composer.
static void ShowMessageComposer (string[] recipients=null, string subject=null, string body=null, EventCallback< MessageComposerResult > callback=null, params ShareItem[] shareItems)
Shows the message composer.
Member Function Documentation
ShowMailComposer()
static void ShowMailComposer (string[] toRecipients = null, string[] ccRecipients = null, string[] bccRecipients = null, string subject = null, string body = null, bool isHtmlBody = false, EventCallback< MailComposerResult > callback = null, params ShareItem[] shareItems) static
Parameters
toRecipients To recipients.
ccRecipients Cc recipients.
bccRecipients Bcc recipients.
subject Subject.
body Body.
isHtmlBody If set to true is html body.
callback Callback.
shareItems Share items.
References MailComposer.CreateInstance(), and MailComposer.Show().
ShowMessageComposer()
static void ShowMessageComposer (string[] recipients = null, string subject = null, string body = null, EventCallback< MessageComposerResult > callback = null, params ShareItem[] shareItems) static
Parameters
recipients Recipients.
subject Subject.
body Body.
callback Callback.
shareItems Share items.
References MessageComposer.CanSendAttachments(), MessageComposer.CanSendSubject(), MessageComposer.CreateInstance(), and MessageComposer.Show().