var class_voxel_busters_1_1_essential_kit_1_1_notification_services_unity_settings =
[
    [ "AndroidPlatformProperties", "d7/db9/class_voxel_busters_1_1_essential_kit_1_1_notification_services_unity_settings_1_1_android_platform_properties.html", "d7/db9/class_voxel_busters_1_1_essential_kit_1_1_notification_services_unity_settings_1_1_android_platform_properties" ]
];