Essential Kit: MediaContentCaptureOptions
MediaContentCaptureOptions
Media Services
Contains options which customize the behavior of the MediaServices.CaptureMediaContent method.
Public Member Functions
MediaContentCaptureOptions (MediaContentCaptureType captureType, string title, string fileName, MediaContentCaptureSource source=MediaContentCaptureSource.Camera)
Initializes a new instance of the MediaContentCaptureOptions class.
Static Public Member Functions
static MediaContentCaptureOptions CreateForImage ()
Creates the options for image capture.
static MediaContentCaptureOptions CreateForVideo ()
Creates the options for video capture.
Properties
MediaContentCaptureType CaptureType [get]
Gets the type of media content.
string Title [get]
Gets the title of the capture.
string FileName [get]
Gets the file name.
MediaContentCaptureSource Source [get, set]
Gets the source of media content.
Constructor & Destructor Documentation
MediaContentCaptureOptions()
MediaContentCaptureOptions (MediaContentCaptureType captureType, string title, string fileName, MediaContentCaptureSource source = MediaContentCaptureSource::Camera)
Parameters
captureType Type of the capture.
title Title of the capture.
fileName File name without extension.
source Source of media content.
References MediaContentCaptureOptions.CaptureType, MediaContentCaptureOptions.FileName, MediaContentCaptureOptions.Source, and MediaContentCaptureOptions.Title.
Referenced by MediaContentCaptureOptions.CreateForImage(), and MediaContentCaptureOptions.CreateForVideo().
Member Function Documentation
CreateForImage()
static MediaContentCaptureOptions CreateForImage () static
Returns
The options for image capture.
References MediaContentCaptureOptions.MediaContentCaptureOptions().
CreateForVideo()
static MediaContentCaptureOptions CreateForVideo () static
Returns
The options for video capture.
References MediaContentCaptureOptions.MediaContentCaptureOptions().
Property Documentation
CaptureType
MediaContentCaptureType CaptureType get
The type of media content.
Referenced by MediaContentCaptureOptions.MediaContentCaptureOptions().
Title
string Title get
The title of the capture.
Referenced by MediaContentCaptureOptions.MediaContentCaptureOptions().
FileName
string FileName get
The file name without extension.
Referenced by MediaContentCaptureOptions.MediaContentCaptureOptions().
Source
MediaContentCaptureSource Source get set
The source of media content.
Referenced by MediaContentCaptureOptions.MediaContentCaptureOptions().