Essential Kit: MediaContentSelectOptions
MediaContentSelectOptions
Media Services
Contains options for selecting media content.
Public Member Functions
MediaContentSelectOptions (string title, string allowedMimeType, int maxAllowed)
Initializes a new instance of the MediaContentSelectOptions class.
Static Public Member Functions
Helpers
static MediaContentSelectOptions CreateForImage (int maxAllowed=1)
Creates options for selecting image.
static MediaContentSelectOptions CreateForVideo (int maxAllowed=1)
Creates options for selecting video.
static MediaContentSelectOptions CreateForAudio (int maxAllowed=1)
Creates options for selecting audio.
static MediaContentSelectOptions CreateForAny (int maxAllowed=1)
Creates options for selecting any file type.
Properties
string Title [get]
Gets the title which is shown to user.
string AllowedMimeType [get]
Gets the allowed mime type.
int MaxAllowed [get]
Gets the max allowed.
Constructor & Destructor Documentation
MediaContentSelectOptions()
MediaContentSelectOptions (string title, string allowedMimeType, int maxAllowed)
Parameters
title Title.
allowedMimeType Allowed mime type.
maxAllowed Max allowed contents to select.
References MediaContentSelectOptions.AllowedMimeType, MediaContentSelectOptions.MaxAllowed, and MediaContentSelectOptions.Title.
Referenced by MediaContentSelectOptions.CreateForAny(), MediaContentSelectOptions.CreateForAudio(), MediaContentSelectOptions.CreateForImage(), and MediaContentSelectOptions.CreateForVideo().
Member Function Documentation
CreateForImage()
static MediaContentSelectOptions CreateForImage (int maxAllowed = 1) static
Returns
The options.
Parameters
maxAllowed Max allowed.
References MediaContentSelectOptions.MediaContentSelectOptions(), and MimeType.kAllImages.
CreateForVideo()
static MediaContentSelectOptions CreateForVideo (int maxAllowed = 1) static
Returns
The options.
Parameters
maxAllowed Max allowed contents.
References MediaContentSelectOptions.MediaContentSelectOptions(), and MimeType.kAllVideos.
CreateForAudio()
static MediaContentSelectOptions CreateForAudio (int maxAllowed = 1) static
Returns
The options.
Parameters
maxAllowed Max allowed.
References MediaContentSelectOptions.MediaContentSelectOptions(), and MimeType.kAllAudio.
CreateForAny()
static MediaContentSelectOptions CreateForAny (int maxAllowed = 1) static
Returns
The options.
Parameters
maxAllowed Max allowed.
References MediaContentSelectOptions.MediaContentSelectOptions(), and MimeType.kAny.
Property Documentation
Title
string Title get
The title.
Referenced by MediaContentSelectOptions.MediaContentSelectOptions().
AllowedMimeType
string AllowedMimeType get
The allowed mime type.
Referenced by MediaContentSelectOptions.MediaContentSelectOptions().
MaxAllowed
int MaxAllowed get
The max allowed.
Referenced by MediaContentSelectOptions.MediaContentSelectOptions().