Essential Kit: AlertDialogBuilder
AlertDialogBuilder
Builder class for AlertDialog objects. Provides a convenient way to set the various fields of a AlertDialog.
Public Member Functions
AlertDialogBuilder (AlertDialogStyle alertStyle=AlertDialogStyle.Default)
Initializes a new instance of the Builder class.
AlertDialogBuilder SetTitle (string value)
Sets the title of the alert.
AlertDialogBuilder SetMessage (string value)
Sets the message of the alert.
AlertDialogBuilder AddButton (string title, Callback callback)
Adds an action button to the alert. Here, the default style is used.
AlertDialogBuilder AddCancelButton (string title, Callback callback)
Adds action button to the alert. This style type indicates the action cancels the operation and leaves things unchanged.
AlertDialog Build ()
Combines all of the options that have been set and return a new AlertDialog object.
Detailed Description
The following code example shows how to configure and present an alert dialog using builder.
using UnityEngine;
using System.Collections;
using VoxelBusters.EssentialKit;
public class ExampleClass : MonoBehaviour
{
    public void Start()
    {
        AlertDialog newDialog   = new Builder()
            .SetTitle(title);
            .SetMessage(message);
            .AddButton(button, OnAlertButtonClicked);
            .Build();
        newDialog.Show();
    }
    private void OnAlertButtonClicked()
    {
        // add your code
    }
}
Constructor & Destructor Documentation
AlertDialogBuilder()
AlertDialogBuilder (AlertDialogStyle alertStyle = AlertDialogStyle::Default)
Parameters
alertStyle The alert style to be used.
References AlertDialog.CreateInstance().
Member Function Documentation
SetTitle()
AlertDialogBuilder SetTitle (string value)
Parameters
value The title of the alert.
SetMessage()
AlertDialogBuilder SetMessage (string value)
Parameters
value The descriptive text that provides more details about the reason for the alert.
AddButton()
AlertDialogBuilder AddButton (string title, Callback callback)
Parameters
title The title of the button.
callback The method to execute when the user selects this button.
References AlertDialog.AddButton().
AddCancelButton()
AlertDialogBuilder AddCancelButton (string title, Callback callback)
Parameters
title The title of the button.
callback The method to execute when the user selects this button.
References AlertDialog.AddCancelButton().
Build()
AlertDialog Build ()
Returns
The build.