Essential Kit: ShareItem
ShareItem
Sharing Services
Class internally used to pass data options into sharing functions.
Static Public Member Functions
static ShareItem Text (string text)
Option used to share a text content.
static ShareItem URL (URLString url)
Option used to share a url.
static ShareItem Image (Texture2D image, TextureEncodingFormat textureEncodingFormat, string fileName)
Option used to share an image content.
static ShareItem File (byte[] data, string mimeType, string fileName)
Option used to share an file content (image).
static ShareItem Screenshot ()
Option used to a share screenshot.
Member Function Documentation
Text()
static ShareItem Text (string text) static
Parameters
text Text.
References ShareItem.Text().
Referenced by ShareItem.Text().
URL()
static ShareItem URL (URLString url) static
Parameters
url URL.
References URLString.IsValid, and ShareItem.URL().
Referenced by ShareItem.URL().
Image()
static ShareItem Image (Texture2D image, TextureEncodingFormat textureEncodingFormat, string fileName) static
Parameters
image Image.
textureEncodingFormat Texture encoding format.
fileName File name.
File()
static ShareItem File (byte[] data, string mimeType, string fileName) static
Parameters
data Image data.
mimeType Mime type.
fileName File name.